#!/bin/sh

PXF_HOME="/usr/local/cloudberry-pxf"
PXF_EXT_DIR="${PXF_HOME}/gpextable"

# Update pxf.control with correct paths
sed -i "s|directory =.*|directory = '${PXF_EXT_DIR}/'|g" "${PXF_EXT_DIR}/pxf.control"
sed -i "s|module_pathname =.*|module_pathname = '${PXF_EXT_DIR}/pxf'|g" "${PXF_EXT_DIR}/pxf.control"